name: pages
permissions:
  contents: write
on:
  push:
    branches: [main]
jobs:
  build_gh_pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run build --ws
    - run: npm run doc
    - name: Copy files to public
      run: |
        mkdir ./public
        cp -r ./docs ./public/docs
        cp -r ./packages/examples/dist ./public/examples
        cp -r ./packages/gltf-viewer/dist ./public/gltf-viewer
    - name: Deploy public
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: latest
        publish_dir: ./public
