name: pages
on: [push]
jobs:
  build_gh_pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci --ignore-scripts
    - run: npm run doc -- --excludeInternal
    - run: npm run build:examples
    - name: Copy files to public
      run: |
        cp -r ./docs ./public
        cp -r ./examples ./public/examples
    - name: Deploy public
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
