name: release
permissions:
  contents: write
on:
  release:
    types: [created]
jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build --ws
    - run: npm test --ws
      env:
        CI: true
    - run: npm run doc
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: docs
        publish_dir: ./docs
    - name: Deploy examples
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: examples
        publish_dir: ./packages/examples/dist
    - name: Deploy gltf-viewer
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: gltf-viewer
        publish_dir: ./packages/gltf-viewer/dist
